@version: 4.0
@include "scl.conf"

options {
    keep_hostname(yes);
    create_dirs(yes);
    flush_lines(1);
};

source s_network {
    udp(ip("0.0.0.0") port(514));
    tcp(ip("0.0.0.0") port(601));
};

destination d_per_host {
    file(
        "/var/log/network/${HOST}/${YEAR}-${MONTH}-${DAY}.log"
        create_dirs(yes)
    );
};

log {
    source(s_network);
    destination(d_per_host);
};
